### ISSUE TITLE
Video tag fails on (previously working) relative URLs

### ISSUE THREAD

**Issue by ghost** [imathis/octopress#1127]
I suppose the problem was introduced in https://github.com/imathis/octopress/commit/8bf09b178d513a264b900186d20f5c0b928c7287

Videos and pictures I use in my posts are stored in a directory "media" inside my "source" folder. My root ist "/", so I'm not facing the problem of https://github.com/imathis/octopress/issues/724 and was using this without any problems so far: `{% video /media/everyday.mp4 480 640 /media/everyday.jpg %}`

After updating octopress today, I'm getting this error:

```
Liquid Exception: undefined method `size' for nil:NilClass in 2012-03-26-everyday-im-mugshooting.markdown
/Users/manu/Documents/octopress/plugins/video_tag.rb:41:in `render'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:94:in `block in render_all'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:92:in `collect'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:92:in `render_all'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:82:in `render'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/template.rb:124:in `render'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/template.rb:132:in `render!'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/convertible.rb:79:in `do_layout'
/Users/manu/Documents/octopress/plugins/post_filters.rb:167:in `do_layout'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/post.rb:195:in `render'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:200:in `block in render'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:199:in `each'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:199:in `render'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:41:in `process'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/bin/jekyll:253:in `block in <top (required)>'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/directory_watcher-1.4.1/lib/directory_watcher.rb:580:in `call'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/directory_watcher-1.4.1/lib/directory_watcher.rb:580:in `block in notify_observers'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/directory_watcher-1.4.1/lib/directory_watcher.rb:579:in `each'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/directory_watcher-1.4.1/lib/directory_watcher.rb:579:in `notify_observers'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/directory_watcher-1.4.1/lib/directory_watcher.rb:334:in `block in initialize'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/directory_watcher-1.4.1/lib/directory_watcher/scanner.rb:224:in `call'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/directory_watcher-1.4.1/lib/directory_watcher/scanner.rb:224:in `notify'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/directory_watcher-1.4.1/lib/directory_watcher/scanner.rb:102:in `run_once'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/directory_watcher-1.4.1/lib/directory_watcher/scanner.rb:150:in `run_loop'
/Users/manu/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/directory_watcher-1.4.1/lib/directory_watcher/scanner.rb:45:in `block in start'
Build Failed
```

When I change the code to `{% video http://manuelgrabowski.de/media/everyday.mp4 480 640 /media/everyday.jpg %}` the error does not occur. I don't like using absolute URLs however, as my domain name might change. I played around with the regex in video_tag.rb for a while but couldn't come up with anything that works, I'm guessing your knowledge of the file will make it easier for you to fix this.

**Comment by mlindgren** [comment]
I am also having this issue.

**Comment by imathis** [comment]
Thanks for the report. I'm taking a look.

**Comment by imathis** [comment]
@lynnard I just ran your example and this is the HTML I got (no errors):

```html
<video  controls poster='/images/visionary-pioneer/visionary-pioneer.png' width='640' height='480' preload='metadata' onclick='(function(el){ if(el.paused) el.play(); else el.pause() })(this)'>
  <source src='/videos/VisionaryPioneer.mp4' type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'></video>
```

Are you sure you have version `1.1.1`?

**Comment by mlindgren** [comment]
Huh, I just checked again and this is also working for me now.  I haven't pulled any changes since last night, so I'm not sure what changed.  Maybe I had a typo somewhere.

**Comment by imathis** [comment]
😱👻~SPOOKY~👻😱
